title: DoctorLogic
email: msparks@doctorlogic.com
description: >- # this means to ignore newlines until "baseurl:"
  DoctorLogic provides online marketing tools for the medical industry, primarily to specialty doctors and dentists who own their practice.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://doctorlogic.com" # the base hostname & protocol for your site, e.g. http://example.com
default-img: /img/meta/dl.jpg
permalink: none

# Build settings
include: ['_pages', '_redirects']
plugins:
  - jekyll-feed
  - octopress-autoprefixer
  - jekyll-sitemap

collections:
  seo_updates:
    output: true
    permalink: /:collection/:title

defaults:
-
  scope:
    path: "" # an empty string here means all files in the project
    type: "posts"
  values:
    layout: "post"
    hs_form_id: "75c57a13-9090-4db1-acd0-be51d1a76f7e"
    permalink: /blog/:title:output_ext
    nofollow: false
-
  scope:
    path: "blog/tag"
  values:
    layout: "tags"
    hs_form_id: "75c57a13-9090-4db1-acd0-be51d1a76f7e"
    page_class: blog-list-page
-
  scope:
    path: "" # an empty string here means all files in the project
    type: "seo_updates"
  values:
    layout: "seo_updates"



